### ISSUE TITLE
elinks: command not found

### ISSUE THREAD

**Issue by touxstone** [jacob-mf/drae#4]
Hi, He estado probando este interesante script pero da error a partir de la línea 77 `elinks -dump 'http://dle.rae.es/'${in}${fu}'' > /tmp/.conjugacion.txt`. El error output es:  `elinks: command not found`.
He comprobado el link en el buscador pero dirección es correcta. 
Alguna pista y volver esta herramienta a la vida? Es muy práctica sería interesante que funcione.
Gracias!!

**Comment by jacob-mf** [comment]
> Hi, He estado probando este interesante script pero da error a partir de la línea 77 `elinks -dump 'http://dle.rae.es/'${in}${fu}'' > /tmp/.conjugacion.txt`. El error output es: `elinks: command not found`. He comprobado el link en el buscador pero dirección es correcta. Alguna pista y volver esta herramienta a la vida? Es muy práctica sería interesante que funcione. Gracias!!

Muchas gracias @touxstone  por probar la herramienta.
El error que comentas es por que la herramienta necesita que estñe instalado el elinks, el navegador de texto,tal como se indica en el README, en el apartado de requisitos:
Requisitos: | Requirements:

Usa paquete 'elinks' (navegador de Internet por texto, versión 0.13.GIT) | Elinks (Text web browser version 0.13.GIT)

Comando 'sed' para lo más complicado de la tarea (GNU sed) 4.7) | Bash command 'sed' (sed (GNU sed) 4.7) 
---
He probado hoy la utilidad y funciona sin problemas, por lo que procedo al cierre de la incidencia.
![image](https://github.com/user-attachments/assets/1417f878-f4ea-44cf-b1eb-653852fbbabf)

Saludos
